spring:
  application:
    name: auth-service
  cloud:
    config:
      enabled: false

server:
  port: 8071

jwt:
  expiry: 18_000_000
  secret: "gouEtIL5NhqqfqyrqIV3Q+JNMzhIKf+g2DPGl5Y1PLthUUKKwojW8Mjj+SMWz+Un\n"

---

spring:
  config:
    activate:
      on-profile: test

---


spring:
  config:
    activate:
      on-profile: prod

---