spring:
  application:
    name: employee-service
  cloud:
    config:
      enabled: false

server:
  port: 8070


---

spring:
  config:
    activate:
      on-profile: test

---


spring:
  config:
    activate:
      on-profile: prod

---