spring:
  application:
    name: employee-service

  jpa:
    hibernate:
      ddl-auto: update

  config:
    import: 'optional:configserver:'
    name: ${spring.application.name}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8080


---

spring:
  config:
    activate:
      on-profile: prod
    import: 'optional:config-server'
    name: ${spring.application.name}

---

spring:
  config:
    activate:
      on-profile: test
    import: 'optional:config-server'
    name: ${spring.application.name}
